import { useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowUpRight, Cpu, Github, Layers, ShieldCheck, X } from 'lucide-react';
import { ArchitectureModal, type ProjectArchitecture } from './ArchitectureModal';
import { PROJECTS, type Project, type ProjectCategory } from '../../lib/projects';

type Category = 'All' | ProjectCategory;
const CATEGORIES: Array<'All' | 'AI vision' | 'Security' | 'Web systems'> = ['All', 'AI vision', 'Security', 'Web systems'];

function CategoryIcon({ category }: { category: Project['category'] }) { return category === 'AI vision' ? <Cpu size={15} /> : category === 'Security' ? <ShieldCheck size={15} /> : <Layers size={15} />; }

export function Projects() {
  const [category, setCategory] = useState<Category>('All');
  const [selected, setSelected] = useState<Project | null>(null);
  const [architecture, setArchitecture] = useState<ProjectArchitecture>();
  const visible = PROJECTS.filter((project) => project.featured && (category === 'All' || project.category === category));
  return <section id="work" className="scroll-mt-[72px] border-b border-[var(--line)] bg-[var(--project-wash)]">
    <div className="mx-auto max-w-[1440px] px-5 py-16 md:px-10 md:py-24">
      <div className="flex flex-col justify-between gap-8 border-b border-[var(--line)] pb-10 lg:flex-row lg:items-end">
        <motion.div initial={{ opacity: 0, y: 26 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}><p className="label-mono text-[var(--accent)]">Project dossiers</p><h2 className="mt-5 max-w-2xl text-4xl font-semibold leading-[0.98] tracking-[-0.05em] md:text-6xl">Repositories grouped by the systems they prove.</h2></motion.div>
        <div className="flex max-w-full gap-2 overflow-x-auto pb-1 no-scrollbar">{CATEGORIES.map((item) => { const isActive = category === item; return <motion.button whileTap={{ scale: 0.96 }} key={item} onClick={() => setCategory(item)} className={`label-mono relative whitespace-nowrap border px-3 py-2 transition-colors ${isActive ? 'border-[var(--accent)] bg-[var(--accent)] text-white' : 'border-[var(--line)] text-[var(--ink-soft)] hover:border-[var(--line-strong)]'}`}>{item}</motion.button>; })}</div>
      </div>
      <div className="mt-8 grid gap-px border border-[var(--line)] bg-[var(--line)] md:grid-cols-2 xl:grid-cols-3">
        <AnimatePresence mode="popLayout">{visible.map((project, index) => <motion.article layout key={project.id} initial={{ opacity: 0, y: 24, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 12, scale: 0.96 }} whileHover={{ y: -8, scale: 1.012 }} transition={{ duration: 0.48, delay: index * 0.055, ease: [0.22, 1, 0.36, 1] }} onClick={() => setSelected(project)} className="project-card group relative flex min-h-[330px] cursor-pointer flex-col justify-between overflow-hidden bg-[var(--card)] p-6 shadow-[0_0_0_rgba(10,18,40,0)] transition-[background-color,box-shadow] hover:bg-[var(--paper-strong)] hover:shadow-[0_18px_45px_rgba(10,18,40,0.12)] md:p-7">
          <motion.div className="pointer-events-none absolute inset-x-0 top-0 h-[3px] origin-left bg-[var(--signal)]" initial={{ scaleX: 0 }} whileInView={{ scaleX: 1 }} transition={{ duration: 0.7, delay: 0.1 + index * 0.05 }} />
          <div><div className="flex items-center justify-between text-[var(--accent)]"><span className="label-mono flex items-center gap-2"><CategoryIcon category={project.category} /> {project.category}</span><motion.a href={project.url} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()} aria-label={`Open ${project.title} on GitHub`} whileHover={{ rotate: 8, scale: 1.08 }} className="border border-[var(--line)] p-2 text-[var(--ink-soft)] hover:text-[var(--accent)]"><Github size={15} /></motion.a></div><h3 className="mt-12 text-2xl font-semibold tracking-[-0.04em] transition-colors group-hover:text-[var(--accent)]">{project.title}</h3><p className="mt-2 text-sm font-medium text-[var(--accent)]">{project.tagline}</p><p className="mt-5 max-w-sm text-sm leading-relaxed text-[var(--ink-soft)]">{project.description}</p></div>
          <div className="flex items-end justify-between border-t border-[var(--line)] pt-5"><div className="flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="border border-[var(--line)] px-2 py-1 font-mono text-[10px] text-[var(--ink-faint)]">{tag}</span>)}</div><span className="label-mono flex items-center gap-1 text-[var(--ink-soft)]">Read dossier <ArrowUpRight size={13} className="transition-transform duration-300 group-hover:-translate-y-1 group-hover:translate-x-1" /></span></div>
        </motion.article>)}</AnimatePresence>
      </div>
       <div className="mt-10 flex flex-col justify-between gap-5 border-t border-[var(--line)] pt-6 text-sm text-[var(--ink-soft)] sm:flex-row"><span>More experiments live in the archive.</span><a href="/projects" className="font-semibold text-[var(--accent)] hover:underline">Open the project archive <ArrowUpRight className="ml-1 inline" size={14} /></a></div>
    </div>
    <AnimatePresence>{selected && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(null)} className="fixed inset-0 z-[60] grid place-items-center bg-[rgba(0,0,0,0.65)] p-4"><motion.div initial={{ y: 16 }} animate={{ y: 0 }} onClick={(event) => event.stopPropagation()} className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto border border-[var(--line-strong)] bg-[var(--paper)] p-6 md:p-10"><button onClick={() => setSelected(null)} className="absolute right-5 top-5 p-2" aria-label="Close project dossier"><X size={18} /></button><p className="label-mono text-[var(--accent)]">{selected.category} / dossier</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em]">{selected.title}</h2><p className="mt-2 text-lg text-[var(--accent)]">{selected.tagline}</p><p className="mt-8 leading-relaxed text-[var(--ink-soft)]">{selected.description}</p><div className="mt-8 flex flex-wrap gap-2">{selected.tags.map((tag) => <span key={tag} className="border border-[var(--line)] px-3 py-2 font-mono text-xs">{tag}</span>)}</div><div className="mt-10 flex flex-wrap gap-3 border-t border-[var(--line)] pt-6"><a href={selected.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-[var(--accent-ink)]">View repository <Github size={15} /></a>{selected.architecture && <button onClick={() => { setArchitecture(selected.architecture); setSelected(null); }} className="inline-flex items-center gap-2 border border-[var(--line-strong)] px-4 py-3 text-sm font-semibold">Open blueprint <Layers size={15} /></button>}</div></motion.div></motion.div>}</AnimatePresence>
    <ArchitectureModal isOpen={Boolean(architecture)} onClose={() => setArchitecture(undefined)} architecture={architecture} />
  </section>;
}
